Document: media-index
Title: Debian media-index Manual
Author: <insert document author here>
Abstract: This manual describes what media-index is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/media-index/media-index.sgml.gz

Format: postscript
Files: /usr/share/doc/media-index/media-index.ps.gz

Format: text
Files: /usr/share/doc/media-index/media-index.text.gz

Format: HTML
Index: /usr/share/doc/media-index/html/index.html
Files: /usr/share/doc/media-index/html/*.html

  
